// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: EggIncubatorType.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Inventory
{

    [global::ProtoBuf.ProtoContract()]
    public enum EggIncubatorType
    {
        INCUBATOR_UNSET = 0,
        INCUBATOR_DISTANCE = 1,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
