// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: ExclusiveTicketInfo.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Inventory
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ExclusiveTicketInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long raid_seed { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string fort_id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        public long start_time_ms { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public long end_time_ms { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string image_url { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7)]
        public double latitude { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public double longitude { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        [global::System.ComponentModel.DefaultValue("")]
        public string gym_name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(10)]
        public long spawn_time_ms { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public bool is_cancelled { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public global::POGOProtos.Data.PokemonData raid_pokemon { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
