// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: InventoryUpgradeType.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Inventory
{

    [global::ProtoBuf.ProtoContract()]
    public enum InventoryUpgradeType
    {
        UPGRADE_UNSET = 0,
        INCREASE_ITEM_STORAGE = 1,
        INCREASE_POKEMON_STORAGE = 2,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
