// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: InventoryItemData.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Inventory
{

    [global::ProtoBuf.ProtoContract()]
    public partial class InventoryItemData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::POGOProtos.Data.PokemonData pokemon_data { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::POGOProtos.Inventory.Item.ItemData item { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public global::POGOProtos.Data.PokedexEntry pokedex_entry { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public global::POGOProtos.Data.Player.PlayerStats player_stats { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public global::POGOProtos.Data.Player.PlayerCurrency player_currency { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public global::POGOProtos.Data.Player.PlayerCamera player_camera { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public InventoryUpgrades inventory_upgrades { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public AppliedItems applied_items { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public EggIncubators egg_incubators { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public Candy candy { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public global::POGOProtos.Data.Quests.Quest quest { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public global::POGOProtos.Data.Avatar.AvatarItem avatar_item { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public RaidTickets raid_tickets { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        public global::POGOProtos.Data.Quests.Quests quests { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
