// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: BackgroundToken.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data
{

    [global::ProtoBuf.ProtoContract()]
    public partial class BackgroundToken : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public byte[] token { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long expiration_time { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public byte[] iv { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
