// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: PlayerData.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long creation_timestamp_ms { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string username { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5)]
        public global::POGOProtos.Enums.TeamColor team { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsPacked = true)]
        public global::System.Collections.Generic.List<global::POGOProtos.Enums.TutorialState> tutorial_state { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Enums.TutorialState>();

        [global::ProtoBuf.ProtoMember(8)]
        public global::POGOProtos.Data.Player.PlayerAvatar avatar { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public int max_pokemon_storage { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public int max_item_storage { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public global::POGOProtos.Data.Player.DailyBonus daily_bonus { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public global::POGOProtos.Data.Player.EquippedBadge equipped_badge { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public global::POGOProtos.Data.Player.ContactSettings contact_settings { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        public global::System.Collections.Generic.List<global::POGOProtos.Data.Player.Currency> currencies { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Data.Player.Currency>();

        [global::ProtoBuf.ProtoMember(15)]
        public int remaining_codename_claims { get; set; }

        [global::ProtoBuf.ProtoMember(16)]
        public BuddyPokemon buddy_pokemon { get; set; }

        [global::ProtoBuf.ProtoMember(17)]
        public long battle_lockout_end_ms { get; set; }

        [global::ProtoBuf.ProtoMember(18)]
        public global::POGOProtos.Data.Player.PlayerAvatar secondary_player_avatar { get; set; }

        [global::ProtoBuf.ProtoMember(19)]
        public bool name_is_blacklisted { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
