// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: PokemonData.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PokemonData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::POGOProtos.Enums.PokemonId pokemon_id { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int cp { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int stamina { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int stamina_max { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public global::POGOProtos.Enums.PokemonMove move_1 { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public global::POGOProtos.Enums.PokemonMove move_2 { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        [global::System.ComponentModel.DefaultValue("")]
        public string deployed_fort_id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(9)]
        [global::System.ComponentModel.DefaultValue("")]
        public string owner_name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(10)]
        public bool is_egg { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public double egg_km_walked_target { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public double egg_km_walked_start { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        public int origin { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public float height_m { get; set; }

        [global::ProtoBuf.ProtoMember(16)]
        public float weight_kg { get; set; }

        [global::ProtoBuf.ProtoMember(17)]
        public int individual_attack { get; set; }

        [global::ProtoBuf.ProtoMember(18)]
        public int individual_defense { get; set; }

        [global::ProtoBuf.ProtoMember(19)]
        public int individual_stamina { get; set; }

        [global::ProtoBuf.ProtoMember(20)]
        public float cp_multiplier { get; set; }

        [global::ProtoBuf.ProtoMember(21)]
        public global::POGOProtos.Inventory.Item.ItemId pokeball { get; set; }

        [global::ProtoBuf.ProtoMember(22)]
        public ulong captured_cell_id { get; set; }

        [global::ProtoBuf.ProtoMember(23)]
        public int battles_attacked { get; set; }

        [global::ProtoBuf.ProtoMember(24)]
        public int battles_defended { get; set; }

        [global::ProtoBuf.ProtoMember(25)]
        [global::System.ComponentModel.DefaultValue("")]
        public string egg_incubator_id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(26)]
        public ulong creation_time_ms { get; set; }

        [global::ProtoBuf.ProtoMember(27)]
        public int num_upgrades { get; set; }

        [global::ProtoBuf.ProtoMember(28)]
        public float additional_cp_multiplier { get; set; }

        [global::ProtoBuf.ProtoMember(29)]
        public int favorite { get; set; }

        [global::ProtoBuf.ProtoMember(30)]
        [global::System.ComponentModel.DefaultValue("")]
        public string nickname { get; set; } = "";

        [global::ProtoBuf.ProtoMember(31)]
        public int from_fort { get; set; }

        [global::ProtoBuf.ProtoMember(32)]
        public int buddy_candy_awarded { get; set; }

        [global::ProtoBuf.ProtoMember(33)]
        public float buddy_total_km_walked { get; set; }

        [global::ProtoBuf.ProtoMember(34)]
        public int display_pokemon_id { get; set; }

        [global::ProtoBuf.ProtoMember(35)]
        public int display_cp { get; set; }

        [global::ProtoBuf.ProtoMember(36)]
        public PokemonDisplay pokemon_display { get; set; }

        [global::ProtoBuf.ProtoMember(37)]
        public bool is_bad { get; set; }

        [global::ProtoBuf.ProtoMember(38)]
        public bool hatched_from_egg { get; set; }

        [global::ProtoBuf.ProtoMember(39)]
        public int coins_returned { get; set; }

        [global::ProtoBuf.ProtoMember(40)]
        public long deployed_duration_ms { get; set; }

        [global::ProtoBuf.ProtoMember(41)]
        public long deployed_returned_timestamp_ms { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
