// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: RedeemPasscodeReward.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data
{

    [global::ProtoBuf.ProtoContract()]
    public partial class RedeemPasscodeReward : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<global::POGOProtos.Data.Redeem.RedeemedItem> items { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Data.Redeem.RedeemedItem>();

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<global::POGOProtos.Data.Redeem.RedeemedAvatarItem> avatar_items { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Data.Redeem.RedeemedAvatarItem>();

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<PokemonData> egg_pokemon { get; } = new global::System.Collections.Generic.List<PokemonData>();

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<PokemonData> pokemon { get; } = new global::System.Collections.Generic.List<PokemonData>();

        [global::ProtoBuf.ProtoMember(5)]
        public global::System.Collections.Generic.List<global::POGOProtos.Data.Redeem.PokeCandy> poke_candy { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Data.Redeem.PokeCandy>();

        [global::ProtoBuf.ProtoMember(6)]
        public int stardust { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public int pokecoins { get; set; }

        [global::ProtoBuf.ProtoMember(8, IsPacked = true)]
        public global::System.Collections.Generic.List<global::POGOProtos.Enums.BadgeType> badges { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Enums.BadgeType>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
