// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: LobbyPokemon.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Map.Pokemon
{

    [global::ProtoBuf.ProtoContract()]
    public partial class LobbyPokemon : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::POGOProtos.Enums.PokemonId pokedex_id { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int cp { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public float percent_health { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
