// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: MotivatedPokemon.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Map.Pokemon
{

    [global::ProtoBuf.ProtoContract()]
    public partial class MotivatedPokemon : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::POGOProtos.Data.PokemonData pokemon { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long deploy_ms { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int cp_when_deployed { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public double motivation_now { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int cp_now { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public float berry_value { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public long feed_cooldown_duration_millis { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public global::System.Collections.Generic.List<global::POGOProtos.Data.FoodValue> food_value { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Data.FoodValue>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
