// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: FriendshipLevelData.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data.Friends
{

    [global::ProtoBuf.ProtoContract()]
    public partial class FriendshipLevelData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long bucket { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int points_earned_today { get; set; }

        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [global::ProtoBuf.ProtoMember(3)]
        public global::POGOProtos.Enums.FriendshipLevelMilestone awarded_friendship_milestone { get; set; }

        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [global::ProtoBuf.ProtoMember(4)]
        public global::POGOProtos.Enums.FriendshipLevelMilestone current_friendship_milestone { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public double next_friendship_milestone_progress_percentage { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int points_toward_next_milestone { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
