// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: IncomingFriendInvite.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data.Friends
{

    [global::ProtoBuf.ProtoContract()]
    public partial class IncomingFriendInvite : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [global::ProtoBuf.ProtoMember(1)]
        public Status status { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string player_id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public long created_ms { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Status
        {
            UNSET = 0,
            PENDING = 1,
            DECLINED = 2,
            CANCELLED = 3,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
