// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: LeveledUpFriends.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data.Friends
{

    [global::ProtoBuf.ProtoContract()]
    public partial class LeveledUpFriends : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<global::POGOProtos.Data.Player.PlayerPublicProfile> friend_profiles { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Data.Player.PlayerPublicProfile>();

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<FriendshipLevelData> friend_milestone_levels { get; } = new global::System.Collections.Generic.List<FriendshipLevelData>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
