// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: CatchPokemonMessage.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Networking.Requests.Messages
{

    [global::ProtoBuf.ProtoContract()]
    public partial class CatchPokemonMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong encounter_id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::POGOProtos.Inventory.Item.ItemId pokeball { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public double normalized_reticle_size { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string spawn_point_id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5)]
        public bool hit_pokemon { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public double spin_modifier { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public double normalized_hit_position { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public global::POGOProtos.Data.ARPlusEncounterValues ar_plus_values { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
