// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: DownloadItemTemplatesMessage.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Networking.Requests.Messages
{

    [global::ProtoBuf.ProtoContract()]
    public partial class DownloadItemTemplatesMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public bool paginate { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int page_offset { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong page_timestamp { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
