// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: GymFeedPokemonMessage.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Networking.Requests.Messages
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GymFeedPokemonMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::POGOProtos.Inventory.Item.ItemId item { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int starting_quantity { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string gym_id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong pokemon_id { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public double player_lat_degrees { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public double player_lng_degrees { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
