// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: ListAvatarCustomizationsMessage.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Networking.Requests.Messages
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ListAvatarCustomizationsMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::POGOProtos.Data.Player.PlayerAvatarType avatar_type { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsPacked = true)]
        public global::System.Collections.Generic.List<global::POGOProtos.Enums.Slot> slot { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Enums.Slot>();

        [global::ProtoBuf.ProtoMember(3, IsPacked = true)]
        public global::System.Collections.Generic.List<global::POGOProtos.Enums.Filter> filters { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Enums.Filter>();

        [global::ProtoBuf.ProtoMember(4)]
        public int start { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int limit { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
