// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: FortData.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Map.Fort
{

    [global::ProtoBuf.ProtoContract()]
    public partial class FortData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public long last_modified_timestamp_ms { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public double latitude { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public double longitude { get; set; }

        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [global::ProtoBuf.ProtoMember(5)]
        public global::POGOProtos.Enums.TeamColor owned_by_team { get; set; }

        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [global::ProtoBuf.ProtoMember(6)]
        public global::POGOProtos.Enums.PokemonId guard_pokemon_id { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public int guard_pokemon_cp { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public bool enabled { get; set; }

        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [global::ProtoBuf.ProtoMember(9)]
        public FortType type { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public long gym_points { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public bool is_in_battle { get; set; }

        [global::ProtoBuf.ProtoMember(12, IsPacked = true)]
        public global::System.Collections.Generic.List<global::POGOProtos.Inventory.Item.ItemId> active_fort_modifier { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Inventory.Item.ItemId>();

        [global::ProtoBuf.ProtoMember(13)]
        public FortLureInfo lure_info { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        public long cooldown_complete_timestamp_ms { get; set; }

        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [global::ProtoBuf.ProtoMember(15)]
        public FortSponsor sponsor { get; set; }

        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [global::ProtoBuf.ProtoMember(16)]
        public FortRenderingType rendering_type { get; set; }

        [global::ProtoBuf.ProtoMember(17)]
        public long deploy_lockout_end_ms { get; set; }

        [global::ProtoBuf.ProtoMember(18)]
        public global::POGOProtos.Data.PokemonDisplay guard_pokemon_display { get; set; }

        [global::ProtoBuf.ProtoMember(19)]
        public bool closed { get; set; }

        [global::ProtoBuf.ProtoMember(20)]
        public global::POGOProtos.Data.Raid.RaidInfo raid_info { get; set; }

        [global::ProtoBuf.ProtoMember(21)]
        public GymDisplay gym_display { get; set; }

        [global::ProtoBuf.ProtoMember(22)]
        public bool visited { get; set; }

        [global::ProtoBuf.ProtoMember(23)]
        public long same_team_deploy_lockout_end_ms { get; set; }

        [global::ProtoBuf.ProtoMember(24)]
        public bool allow_checkin { get; set; }

        [global::ProtoBuf.ProtoMember(25)]
        [global::System.ComponentModel.DefaultValue("")]
        public string image_url { get; set; } = "";

        [global::ProtoBuf.ProtoMember(26)]
        public bool in_event { get; set; }

        [global::ProtoBuf.ProtoMember(27)]
        [global::System.ComponentModel.DefaultValue("")]
        public string banner_url { get; set; } = "";

        [global::ProtoBuf.ProtoMember(28)]
        [global::System.ComponentModel.DefaultValue("")]
        public string partner_id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(30)]
        public bool challenge_quest_completed { get; set; }

        [global::ProtoBuf.ProtoMember(31)]
        public bool is_ex_raid_eligible { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
