// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: FortSponsor.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Map.Fort
{

    [global::ProtoBuf.ProtoContract()]
    public enum FortSponsor
    {
        UNSET_SPONSOR = 0,
        MCDONALDS = 1,
        POKEMON_STORE = 2,
        TOHO = 3,
        SOFTBANK = 4,
        GLOBE = 5,
        SPATULA = 6,
        THERMOMETER = 7,
        KNIFE = 8,
        GRILL = 9,
        SMOKER = 10,
        PAN = 11,
        BBQ = 12,
        FRYER = 13,
        STEAMER = 14,
        HOOD = 15,
        SLOWCOOKER = 16,
        MIXER = 17,
        SCOOPER = 18,
        MUFFINTIN = 19,
        SALAMANDER = 20,
        PLANCHA = 21,
        NIA_OPS = 22,
        WHISK = 23,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
