// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: GymDisplay.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Map.Fort
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GymDisplay : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<GymEvent> gym_event { get; } = new global::System.Collections.Generic.List<GymEvent>();

        [global::ProtoBuf.ProtoMember(2)]
        public int total_gym_cp { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public double lowest_pokemon_motivation { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int slots_available { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public long occupied_millis { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
