// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: AwardFreeRaidTicketResponse.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Networking.Responses
{

    [global::ProtoBuf.ProtoContract()]
    public partial class AwardFreeRaidTicketResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [global::ProtoBuf.ProtoMember(1)]
        public Result result { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Result
        {
            NO_RESULT_SET = 0,
            SUCCESS = 1,
            ERROR_PLAYER_DOES_NOT_MEET_MIN_LEVEL = 2,
            ERROR_DAILY_TICKET_ALREADY_AWARDED = 3,
            ERROR_PLAYER_OUT_OF_RANGE = 4,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
