// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: CatchPokemonResponse.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Networking.Responses
{

    [global::ProtoBuf.ProtoContract()]
    public partial class CatchPokemonResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public CatchStatus status { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public double miss_percent { get; set; }

        [global::ProtoBuf.ProtoMember(3, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong captured_pokemon_id { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public global::POGOProtos.Data.Capture.CaptureAward capture_award { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public CaptureReason capture_reason { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int display_pokedex_id { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public int throws_remaining { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public global::POGOProtos.Data.PokemonDisplay pokemon_display { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum CatchStatus
        {
            CATCH_ERROR = 0,
            CATCH_SUCCESS = 1,
            CATCH_ESCAPE = 2,
            CATCH_FLEE = 3,
            CATCH_MISSED = 4,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum CaptureReason
        {
            UNSET = 0,
            DEFAULT = 1,
            ELEMENTAL_BADGE = 2,
            CRITICAL_CATCH = 3,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
