// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: ClaimCodenameResponse.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Networking.Responses
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ClaimCodenameResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string codename { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string user_message { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public bool is_assignable { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public Status status { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public global::POGOProtos.Data.PlayerData updated_player { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public global::System.Collections.Generic.List<string> suggested_codenames { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoContract()]
        public enum Status
        {
            UNSET = 0,
            SUCCESS = 1,
            CODENAME_NOT_AVAILABLE = 2,
            CODENAME_NOT_VALID = 3,
            CURRENT_OWNER = 4,
            CODENAME_CHANGE_NOT_ALLOWED = 5,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
