// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: CompleteQuestResponse.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Networking.Responses
{

    [global::ProtoBuf.ProtoContract()]
    public partial class CompleteQuestResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [global::ProtoBuf.ProtoMember(1)]
        public Status status { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::POGOProtos.Data.Quests.ClientQuest quest { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<global::POGOProtos.Data.Quests.QuestStamp> stamp { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Data.Quests.QuestStamp>();

        [global::ProtoBuf.ProtoContract()]
        public enum Status
        {
            UNSET = 0,
            SUCCESS = 1,
            ERROR_QUEST_NOT_FOUND = 2,
            ERROR_QUEST_STILL_IN_PROGRESS = 3,
            ERROR_QUEST_ALREADY_COMPLETED = 4,
            ERROR_SUBQUEST_NOT_FOUND = 5,
            ERROR_SUBQUEST_STILL_IN_PROGRESS = 6,
            ERROR_SUBQUEST_ALREADY_COMPLETED = 7,
            ERROR_MULTIPART_STILL_IN_PROGRESS = 8,
            ERROR_MULTIPART_ALREADY_COMPLETED = 9,
            ERROR_REDEEM_COMPLETED_QUEST_STAMP_CARD_FIRST = 10,
            ERROR_INVENTORY_FULL = 11,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
