// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: EvolvePokemonResponse.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Networking.Responses
{

    [global::ProtoBuf.ProtoContract()]
    public partial class EvolvePokemonResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Result result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::POGOProtos.Data.PokemonData evolved_pokemon_data { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int experience_awarded { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int candy_awarded { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Result
        {
            UNSET = 0,
            SUCCESS = 1,
            FAILED_POKEMON_MISSING = 2,
            FAILED_INSUFFICIENT_RESOURCES = 3,
            FAILED_POKEMON_CANNOT_EVOLVE = 4,
            FAILED_POKEMON_IS_DEPLOYED = 5,
            FAILED_INVALID_ITEM_REQUIREMENT = 6,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
