// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: FortSearchResponse.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Networking.Responses
{

    [global::ProtoBuf.ProtoContract()]
    public partial class FortSearchResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [global::ProtoBuf.ProtoMember(1)]
        public Result result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<global::POGOProtos.Inventory.Item.ItemAward> items_awarded { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Inventory.Item.ItemAward>();

        [global::ProtoBuf.ProtoMember(3)]
        public int gems_awarded { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public global::POGOProtos.Data.PokemonData pokemon_data_egg { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int experience_awarded { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public long cooldown_complete_timestamp_ms { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public int chain_hack_sequence_number { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public global::POGOProtos.Data.Badge.AwardedGymBadge awarded_gym_badge { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public global::POGOProtos.Inventory.Loot loot { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public global::POGOProtos.Inventory.Loot bonus_loot { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public int raid_tickets { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public global::POGOProtos.Inventory.Loot team_bonus_loot { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        [global::System.ComponentModel.DefaultValue("")]
        public string fort_id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(14)]
        public global::POGOProtos.Data.Quests.ClientQuest challenge_quest { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public global::POGOProtos.Data.Gift.GiftBox gift_box { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Result
        {
            NO_RESULT_SET = 0,
            SUCCESS = 1,
            OUT_OF_RANGE = 2,
            IN_COOLDOWN_PERIOD = 3,
            INVENTORY_FULL = 4,
            EXCEEDED_DAILY_LIMIT = 5,
            POI_INACCESSIBLE = 6,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
