// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: FortDetailsResponse.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Networking.Responses
{

    [global::ProtoBuf.ProtoContract()]
    public partial class FortDetailsResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string fort_id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public global::POGOProtos.Enums.TeamColor team_color { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public global::POGOProtos.Data.PokemonData pokemon_data { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5)]
        public global::System.Collections.Generic.List<string> image_urls { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(6)]
        public int fp { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public int stamina { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public int max_stamina { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public global::POGOProtos.Map.Fort.FortType type { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public double latitude { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public double longitude { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        [global::System.ComponentModel.DefaultValue("")]
        public string description { get; set; } = "";

        [global::ProtoBuf.ProtoMember(13)]
        public global::System.Collections.Generic.List<global::POGOProtos.Map.Fort.FortModifier> modifiers { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Map.Fort.FortModifier>();

        [global::ProtoBuf.ProtoMember(14)]
        public bool close_soon { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        [global::System.ComponentModel.DefaultValue("")]
        public string checkin_image_url { get; set; } = "";

        [global::ProtoBuf.ProtoMember(16)]
        public global::POGOProtos.Data.Raid.EventInfo event_info { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
