// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: GetAssetDigestResponse.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Networking.Responses
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GetAssetDigestResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<global::POGOProtos.Data.AssetDigestEntry> digest { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Data.AssetDigestEntry>();

        [global::ProtoBuf.ProtoMember(2)]
        public ulong timestamp_ms { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public Result result { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int page_offset { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Result
        {
            UNSET = 0,
            SUCCESS = 1,
            PAGE = 2,
            RETRY = 3,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
