// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: GetGymDetailsResponse.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Networking.Responses
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GetGymDetailsResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::POGOProtos.Data.Gym.GymState gym_state { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<string> urls { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(4)]
        public Result result { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string description { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6)]
        public global::System.Collections.Generic.List<string> secondary_url { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue("")]
        public string checkin_image_url { get; set; } = "";

        [global::ProtoBuf.ProtoMember(8)]
        public global::POGOProtos.Data.Raid.EventInfo event_info { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Result
        {
            UNSET = 0,
            SUCCESS = 1,
            ERROR_NOT_IN_RANGE = 2,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
