// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: GetHatchedEggsResponse.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Networking.Responses
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GetHatchedEggsResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public bool success { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.FixedSize, IsPacked = true)]
        public ulong[] pokemon_id { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsPacked = true)]
        public int[] experience_awarded { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsPacked = true)]
        public int[] candy_awarded { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsPacked = true)]
        public int[] stardust_awarded { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsPacked = true)]
        public float[] egg_km_walked { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public global::System.Collections.Generic.List<global::POGOProtos.Data.PokemonData> hatched_pokemon { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Data.PokemonData>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
