// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: GetIncensePokemonResponse.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Networking.Responses
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GetIncensePokemonResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Result result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::POGOProtos.Enums.PokemonId pokemon_id { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public double latitude { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public double longitude { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string encounter_location { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong encounter_id { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public long disappear_timestamp_ms { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public global::POGOProtos.Data.PokemonDisplay pokemon_display { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Result
        {
            INCENSE_ENCOUNTER_UNKNOWN = 0,
            INCENSE_ENCOUNTER_AVAILABLE = 1,
            INCENSE_ENCOUNTER_NOT_AVAILABLE = 2,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
