// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: GetMapObjectsResponse.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Networking.Responses
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GetMapObjectsResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<global::POGOProtos.Map.MapCell> map_cells { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Map.MapCell>();

        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [global::ProtoBuf.ProtoMember(2)]
        public global::POGOProtos.Map.MapObjectsStatus status { get; set; }

        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [global::ProtoBuf.ProtoMember(3)]
        public TimeOfDay time_of_day { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<global::POGOProtos.Map.Weather.ClientWeather> client_weather { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Map.Weather.ClientWeather>();

        [global::ProtoBuf.ProtoContract()]
        public enum TimeOfDay
        {
            NONE = 0,
            DAY = 1,
            NIGHT = 2,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
