// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: GetRaidDetailsResponse.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Networking.Responses
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GetRaidDetailsResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::POGOProtos.Data.Raid.Lobby lobby { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::POGOProtos.Data.Battle.Battle raid_battle { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public bool player_can_join_lobby { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public Result result { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public global::POGOProtos.Data.Raid.RaidInfo raid_info { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public bool ticket_used { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public bool free_ticket_available { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public int throws_remaining { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public bool received_rewards { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public int num_players_in_lobby { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public long server_ms { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Result
        {
            UNSET = 0,
            SUCCESS = 1,
            ERROR_NOT_IN_RANGE = 2,
            ERROR_RAID_COMPLETED = 3,
            ERROR_RAID_UNAVAILABLE = 4,
            ERROR_PLAYER_BELOW_MINIMUM_LEVEL = 5,
            ERROR_POI_INACCESSIBLE = 6,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
