// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: GiftDetailsResponse.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Networking.Responses
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GiftDetailsResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Result result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<global::POGOProtos.Data.Gift.GiftBoxDetails> gift_boxes { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Data.Gift.GiftBoxDetails>();

        [global::ProtoBuf.ProtoContract()]
        public enum Result
        {
            UNSET = 0,
            SUCCESS = 1,
            ERROR_UNKNOWN = 2,
            ERROR_GIFT_DOES_NOT_EXIST = 3,
            ERROR_INVALID_PLAYER_ID = 4,
            ERROR_FRIEND_NOT_FOUND = 5,
            ERROR_FORT_SEARCH = 6,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
