// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: GymFeedPokemonResponse.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Networking.Responses
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GymFeedPokemonResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [global::ProtoBuf.ProtoMember(1)]
        public Result result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::POGOProtos.Data.Gym.GymStatusAndDefenders gym_status_and_defenders { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public global::POGOProtos.Data.Badge.AwardedGymBadge awarded_gym_badge { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int stardust_awarded { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int xp_awarded { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int num_candy_awarded { get; set; }

        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [global::ProtoBuf.ProtoMember(7)]
        public global::POGOProtos.Enums.PokemonFamilyId family_candy_id { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public long cooldown_complete { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Result
        {
            UNSET = 0,
            SUCCESS = 1,
            ERROR_CANNOT_USE = 2,
            ERROR_NOT_IN_RANGE = 3,
            ERROR_POKEMON_NOT_THERE = 4,
            ERROR_POKEMON_FULL = 5,
            ERROR_NO_BERRIES_LEFT = 6,
            ERROR_WRONG_TEAM = 7,
            ERROR_WRONG_COUNT = 8,
            ERROR_TOO_FAST = 9,
            ERROR_TOO_FREQUENT = 10,
            ERROR_GYM_BUSY = 11,
            ERROR_RAID_ACTIVE = 12,
            ERROR_GYM_CLOSED = 13,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
