// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: OpenTradingResponse.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Networking.Responses
{

    [global::ProtoBuf.ProtoContract()]
    public partial class OpenTradingOutProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Result result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::POGOProtos.Data.Trading.Trading trading { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Result
        {
            UNSET = 0,
            SUCCESS = 1,
            ERROR_UNKNOWN = 2,
            ERROR_FRIEND_NOT_FOUND = 3,
            ERROR_INVALID_PLAYER_ID = 4,
            ERROR_INVALID_STATE = 5,
            ERROR_STATE_HANDLER = 6,
            ERROR_TRADING_EXPIRED = 7,
            ERROR_TRADING_COOLDOWN = 8,
            ERROR_PLAYER_ALREADY_OPENED = 9,
            ERROR_FRIEND_OUT_OF_RANGE = 10,
            ERROR_PLAYER_BELOW_MINIMUM_LEVEL = 11,
            ERROR_PLAYER_REACHED_DAILY_LIMIT = 12,
            ERROR_FRIEND_REACHED_DAILY_LIMIT = 13,
            ERROR_PLAYER_NOT_ENOUGH_STARDUST = 14,
            ERROR_FRIEND_NOT_ENOUGH_STARDUST = 15,
            ERROR_FRIEND_BELOW_MINIMUM_LEVEL = 16,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
