// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: OpenGiftResponse.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Networking.Responses
{

    [global::ProtoBuf.ProtoContract()]
    public partial class OpenGiftResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Result result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::POGOProtos.Inventory.Loot items { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public global::POGOProtos.Data.PokemonData egg_pokemon { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public global::POGOProtos.Data.Friends.FriendshipLevelData updated_friendship_data { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public global::POGOProtos.Data.Player.PlayerPublicProfile friend_profile { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Result
        {
            UNSET = 0,
            SUCCESS = 1,
            ERROR_UNKNOWN = 2,
            ERROR_PLAYER_BAG_FULL = 3,
            ERROR_PLAYER_LIMIT_REACHED = 4,
            ERROR_GIFT_DOES_NOT_EXIST = 5,
            ERROR_FRIEND_NOT_FOUND = 6,
            ERROR_INVALID_PLAYER_ID = 7,
            ERROR_FRIEND_UPDATE = 8,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
