// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: StartRaidBattleResponse.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Networking.Responses
{

    [global::ProtoBuf.ProtoContract()]
    public partial class StartRaidBattleResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [global::ProtoBuf.ProtoMember(1)]
        public Result result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::POGOProtos.Data.Battle.Battle battle { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Result
        {
            UNSET = 0,
            SUCCESS = 1,
            ERROR_GYM_NOT_FOUND = 2,
            ERROR_RAID_UNAVAILABLE = 3,
            ERROR_RAID_COMPLETED = 4,
            ERROR_INVALID_ATTACKERS = 5,
            ERROR_PLAYER_BELOW_MINIMUM_LEVEL = 6,
            ERROR_NOT_IN_RANGE = 7,
            ERROR_POI_INACCESSIBLE = 8,
            ERROR_LOBBY_NOT_FOUND = 9,
            ERROR_NO_TICKET = 10,
            ERROR_INVALID_SERVER = 11,
            ERROR_NEVER_JOINED_BATTLE = 12,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
