// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: UpdateTradingResponse.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Networking.Responses
{

    [global::ProtoBuf.ProtoContract()]
    public partial class UpdateTradingResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [global::ProtoBuf.ProtoMember(1)]
        public Result result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::POGOProtos.Data.Trading.Trading trading { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Result
        {
            UNSET = 0,
            SUCCESS = 1,
            ERROR_UNKNOWN = 2,
            ERROR_FRIEND_NOT_FOUND = 3,
            ERROR_INVALID_PLAYER_ID = 4,
            ERROR_INVALID_STATE = 5,
            ERROR_STATE_HANDLER = 6,
            ERROR_INVALID_POKEMON = 7,
            ERROR_INSUFFICIENT_PAYMENT = 8,
            ERROR_TRADING_EXPIRED = 9,
            ERROR_TRADING_FINISHED = 10,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
