// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: UseItemEncounterResponse.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Networking.Responses
{

    [global::ProtoBuf.ProtoContract()]
    public partial class UseItemEncounterResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [global::ProtoBuf.ProtoMember(1)]
        public Status status { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::POGOProtos.Data.Capture.CaptureProbability capture_probability { get; set; }

        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [global::ProtoBuf.ProtoMember(3)]
        public global::POGOProtos.Inventory.Item.ItemId active_item { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Status
        {
            SUCCESS = 0,
            ALREADY_COMPLETED = 1,
            ACTIVE_ITEM_EXISTS = 2,
            NO_ITEM_IN_INVENTORY = 3,
            INVALID_ITEM_CATEGORY = 4,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
