// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: UseItemEggIncubatorResponse.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Networking.Responses
{

    [global::ProtoBuf.ProtoContract()]
    public partial class UseItemEggIncubatorResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Result result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::POGOProtos.Inventory.EggIncubator egg_incubator { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Result
        {
            UNSET = 0,
            SUCCESS = 1,
            ERROR_INCUBATOR_NOT_FOUND = 2,
            ERROR_POKEMON_EGG_NOT_FOUND = 3,
            ERROR_POKEMON_ID_NOT_EGG = 4,
            ERROR_INCUBATOR_ALREADY_IN_USE = 5,
            ERROR_POKEMON_ALREADY_INCUBATING = 6,
            ERROR_INCUBATOR_NO_USES_REMAINING = 7,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
