// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: UseIncenseResponse.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Networking.Responses
{

    [global::ProtoBuf.ProtoContract()]
    public partial class UseIncenseResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [global::ProtoBuf.ProtoMember(1)]
        public Result result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::POGOProtos.Inventory.AppliedItem applied_incense { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Result
        {
            UNKNOWN = 0,
            SUCCESS = 1,
            INCENSE_ALREADY_ACTIVE = 2,
            NONE_IN_INVENTORY = 3,
            LOCATION_UNSET = 4,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
