// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: Lobby.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data.Raid
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Lobby : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsPacked = true)]
        public int[] lobby_id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<global::POGOProtos.Data.Battle.BattleParticipant> players { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Data.Battle.BattleParticipant>();

        [global::ProtoBuf.ProtoMember(3)]
        public long player_join_end_ms { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public long pokemon_selection_end_ms { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public long raid_battle_start_ms { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public long raid_battle_end_ms { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        [global::System.ComponentModel.DefaultValue("")]
        public string raid_battle_id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(9)]
        [global::System.ComponentModel.DefaultValue("")]
        public string owner_nickname { get; set; } = "";

        [global::ProtoBuf.ProtoMember(10)]
        public bool @private { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public long creation_ms { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public int battle_plfe_instance { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public global::POGOProtos.Enums.WeatherCondition weather_condition { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
