// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: Participation.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data.Raid
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Participation : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int individual_damage_pokeballs { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int team_damage_pokeballs { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int gym_ownership_pokeballs { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int base_pokeballs { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public double blue_percentage { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public double red_percentage { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public double yellow_percentage { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public float bonus_item_multiplier { get; set; }

        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [global::ProtoBuf.ProtoMember(9)]
        public global::POGOProtos.Enums.FriendshipLevelMilestone highest_friendship_milestone { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public int highest_friendship_pokeballs { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
