// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: Raid.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data.Raid
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Raid : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long raid_seed { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long started_ms { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public long completed_ms { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public global::POGOProtos.Enums.PokemonId encounter_pokemon_id { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public bool completed_battle { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public bool received_rewards { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public bool finished_encounter { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public bool received_default_rewards { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public bool incremented_raid_friends { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
