// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: RaidEncounter.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data.Raid
{

    [global::ProtoBuf.ProtoContract()]
    public partial class RaidEncounter : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::POGOProtos.Data.PokemonData pokemon { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long encounter_id { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string spawnpoint_id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        public global::POGOProtos.Data.Capture.CaptureProbability capture_probabilities { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int throws_remaining { get; set; }

        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [global::ProtoBuf.ProtoMember(6)]
        public global::POGOProtos.Enums.RaidLevel raid_level { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue("")]
        public string fort_id { get; set; } = "";

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
