// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: MapCell.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Map
{

    [global::ProtoBuf.ProtoContract()]
    public partial class MapCell : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong s2_cell_id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long current_timestamp_ms { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<global::POGOProtos.Map.Fort.FortData> forts { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Map.Fort.FortData>();

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<SpawnPoint> spawn_points { get; } = new global::System.Collections.Generic.List<SpawnPoint>();

        [global::ProtoBuf.ProtoMember(6)]
        public global::System.Collections.Generic.List<string> deleted_objects { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(7)]
        public bool is_truncated_list { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public global::System.Collections.Generic.List<global::POGOProtos.Map.Fort.FortSummary> fort_summaries { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Map.Fort.FortSummary>();

        [global::ProtoBuf.ProtoMember(9)]
        public global::System.Collections.Generic.List<SpawnPoint> decimated_spawn_points { get; } = new global::System.Collections.Generic.List<SpawnPoint>();

        [global::ProtoBuf.ProtoMember(5)]
        public global::System.Collections.Generic.List<global::POGOProtos.Map.Pokemon.WildPokemon> wild_pokemons { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Map.Pokemon.WildPokemon>();

        [global::ProtoBuf.ProtoMember(10)]
        public global::System.Collections.Generic.List<global::POGOProtos.Map.Pokemon.MapPokemon> catchable_pokemons { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Map.Pokemon.MapPokemon>();

        [global::ProtoBuf.ProtoMember(11)]
        public global::System.Collections.Generic.List<global::POGOProtos.Map.Pokemon.NearbyPokemon> nearby_pokemons { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Map.Pokemon.NearbyPokemon>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
