// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: CameraSettings.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Settings.Master
{

    [global::ProtoBuf.ProtoContract()]
    public partial class CameraSettings : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string next_camera { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, IsPacked = true)]
        public global::System.Collections.Generic.List<global::POGOProtos.Enums.CameraInterpolation> interpolation { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Enums.CameraInterpolation>();

        [global::ProtoBuf.ProtoMember(3, IsPacked = true)]
        public global::System.Collections.Generic.List<global::POGOProtos.Enums.CameraTarget> target_type { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Enums.CameraTarget>();

        [global::ProtoBuf.ProtoMember(4, IsPacked = true)]
        public float[] ease_in_speed { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsPacked = true)]
        public float[] ease_out_speed { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsPacked = true)]
        public float[] duration_seconds { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsPacked = true)]
        public float[] wait_seconds { get; set; }

        [global::ProtoBuf.ProtoMember(8, IsPacked = true)]
        public float[] transition_seconds { get; set; }

        [global::ProtoBuf.ProtoMember(9, IsPacked = true)]
        public float[] angle_degree { get; set; }

        [global::ProtoBuf.ProtoMember(10, IsPacked = true)]
        public float[] angle_offset_degree { get; set; }

        [global::ProtoBuf.ProtoMember(11, IsPacked = true)]
        public float[] pitch_degree { get; set; }

        [global::ProtoBuf.ProtoMember(12, IsPacked = true)]
        public float[] pitch_offset_degree { get; set; }

        [global::ProtoBuf.ProtoMember(13, IsPacked = true)]
        public float[] roll_degree { get; set; }

        [global::ProtoBuf.ProtoMember(14, IsPacked = true)]
        public float[] distance_meters { get; set; }

        [global::ProtoBuf.ProtoMember(15, IsPacked = true)]
        public float[] height_percent { get; set; }

        [global::ProtoBuf.ProtoMember(16, IsPacked = true)]
        public float[] vert_ctr_ratio { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
