// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: EquippedBadgeSettings.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Settings.Master
{

    [global::ProtoBuf.ProtoContract()]
    public partial class EquippedBadgeSettings : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long equip_badge_cooldown_ms { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsPacked = true)]
        public float[] catch_probability_bonus { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsPacked = true)]
        public float[] flee_probability_bonus { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
