// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: EventBadgeSettings.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Settings.Master
{

    [global::ProtoBuf.ProtoContract()]
    public partial class EventBadgeSettings : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long valid_from_ms { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long valid_to_ms { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsPacked = true)]
        public global::System.Collections.Generic.List<global::POGOProtos.Enums.BadgeType> mutually_exclusive_badges { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Enums.BadgeType>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
