// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: GymBadgeGmtSettings.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Settings.Master
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GymBadgeGmtSettings : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsPacked = true)]
        public int[] target { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public float battle_winning_score_per_defender_cp { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public float gym_defending_score_per_minute { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int berry_feeding_score { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int pokemon_deploy_score { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int raid_battle_winning_score { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public int lose_all_battles_score { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
