// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: GymBattleSettings.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Settings.Master
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GymBattleSettings : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public float energy_per_sec { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public float dodge_energy_cost { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public float retarget_seconds { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public float enemy_attack_interval { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public float attack_server_interval { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public float round_duration_seconds { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public float bonus_time_per_ally_seconds { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public int maximum_attackers_per_battle { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public float same_type_attack_bonus_multiplier { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public int maximum_energy { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public float energy_delta_per_health_lost { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public int dodge_duration_ms { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public int minimum_player_level { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        public int swap_duration_ms { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public float dodge_damage_reduction_percent { get; set; }

        [global::ProtoBuf.ProtoMember(16)]
        public int minimum_raid_player_level { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
