// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: IapSettings.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Settings.Master
{

    [global::ProtoBuf.ProtoContract()]
    public partial class IapSettings : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int daily_bonus_coins { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsPacked = true)]
        public int[] daily_defender_bonus_per_pokemon { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int daily_defender_bonus_max_defenders { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<string> daily_defender_bonus_currency { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(5)]
        public long min_time_between_claims_ms { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public bool daily_bonus_enabled { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public bool daily_defender_bonus_enabled { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
