// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: ItemSettings.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Settings.Master
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ItemSettings : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [global::ProtoBuf.ProtoMember(1)]
        public global::POGOProtos.Inventory.Item.ItemId item_id { get; set; }

        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [global::ProtoBuf.ProtoMember(2)]
        public global::POGOProtos.Inventory.Item.ItemType item_type { get; set; }

        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [global::ProtoBuf.ProtoMember(3)]
        public global::POGOProtos.Enums.ItemCategory category { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public float drop_freq { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int drop_trainer_level { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public global::POGOProtos.Settings.Master.Item.PokeballAttributes pokeball { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public global::POGOProtos.Settings.Master.Item.PotionAttributes potion { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public global::POGOProtos.Settings.Master.Item.ReviveAttributes revive { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public global::POGOProtos.Settings.Master.Item.BattleAttributes battle { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public global::POGOProtos.Settings.Master.Item.FoodAttributes food { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public global::POGOProtos.Settings.Master.Item.InventoryUpgradeAttributes inventory_upgrade { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public global::POGOProtos.Settings.Master.Item.ExperienceBoostAttributes xp_boost { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public global::POGOProtos.Settings.Master.Item.IncenseAttributes incense { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        public global::POGOProtos.Settings.Master.Item.EggIncubatorAttributes egg_incubator { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public global::POGOProtos.Settings.Master.Item.FortModifierAttributes fort_modifier { get; set; }

        [global::ProtoBuf.ProtoMember(16)]
        public global::POGOProtos.Settings.Master.Item.StardustBoostAttributes stardust_boost { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
