// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: MoveSettings.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Settings.Master
{

    [global::ProtoBuf.ProtoContract()]
    public partial class MoveSettings : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::POGOProtos.Enums.PokemonMove movement_id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int animation_id { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public global::POGOProtos.Enums.PokemonType pokemon_type { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public float power { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public float accuracy_chance { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public float critical_chance { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public float heal_scalar { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public float stamina_loss_scalar { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public int trainer_level_min { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public int trainer_level_max { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        [global::System.ComponentModel.DefaultValue("")]
        public string vfx_name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(12)]
        public int duration_ms { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public int damage_window_start_ms { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        public int damage_window_end_ms { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public int energy_delta { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
