// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: PlayerLevelSettings.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Settings.Master
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerLevelSettings : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsPacked = true)]
        public int[] rank_num { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsPacked = true)]
        public int[] required_experience { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsPacked = true)]
        public float[] cp_multiplier { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int max_egg_player_level { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int max_encounter_player_level { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int max_raid_encounter_player_level { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public int max_quest_encounter_player_level { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
