// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: PokemonScaleSetting.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Settings.Master
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PokemonScaleSetting : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public PokemonScaleMode pokemon_scale_mode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public float min_height { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public float max_height { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum PokemonScaleMode
        {
            NaturalScale = 0,
            GuiScale = 1,
            BattlePokemonScale = 2,
            RaidBossScale = 3,
            GymTopperScale = 4,
            MapPokemonScale = 5,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
