// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: WeatherBonus.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Settings.Master
{

    [global::ProtoBuf.ProtoContract()]
    public partial class WeatherBonus : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int cp_base_level_bonus { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int guaranteed_individual_values { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public double stardust_bonus_multiplier { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public double attack_bonus_multiplier { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int raid_encounter_cp_base_level_bonus { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int raid_encounter_guaranteed_individual_values { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
