// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: ExcludedPokemon.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data.Trading
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ExcludedPokemon : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong pokemon_id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ExclusionReason exclusion_reason { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum ExclusionReason
        {
            UNSET = 0,
            MYTHICAL_POKEMON = 1,
            SLASHED = 2,
            GYM_DEPLOYED = 3,
            BUDDY = 4,
            STAMINA_NOT_FULL = 5,
            EGG_NOT_HATCHED = 6,
            FRIENDSHIP_LEVEL_LOW = 7,
            FRIEND_CANNOT_AFFORD = 8,
            FRIEND_REACHED_DAILY_LIMIT = 9,
            ALREADY_TRADED = 10,
            PLAYER_CANNOT_AFFORD = 11,
            PLAYER_REACHED_DAILY_LIMIT = 12,
            FAVORITE = 13,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
