// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: Trading.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data.Trading
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Trading : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [global::ProtoBuf.ProtoMember(1)]
        public TradingState state { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong expiration_ms { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public TradingPlayer player { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public TradingPlayer friend { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public long trading_s2_cell_id { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string transaction_log { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7)]
        public global::POGOProtos.Data.Friends.FriendshipLevelData friendship_level_data { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public bool is_special_trading { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public global::POGOProtos.Data.Friends.FriendshipLevelData pre_trading_friendship_level { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum TradingState
        {
            UNSET = 0,
            PRIMORDIAL = 1,
            WAIT = 2,
            ACTIVE = 3,
            CONFIRMED = 4,
            FINISHED = 5,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
