// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: AwardedGymBadge.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data.Badge
{

    [global::ProtoBuf.ProtoContract()]
    public partial class AwardedGymBadge : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string fort_id { get; set; } = "";

        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [global::ProtoBuf.ProtoMember(2)]
        public global::POGOProtos.Enums.GymBadgeType gym_badge_type { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint score { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public GymBadgeStats gym_badge_stats { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public ulong last_update_timestamp_ms { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public ulong last_check_timestamp_ms { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public uint earned_points { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public float progress { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        public bool level_up { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue("")]
        public string image_url { get; set; } = "";

        [global::ProtoBuf.ProtoMember(8)]
        [global::System.ComponentModel.DefaultValue("")]
        public string description { get; set; } = "";

        [global::ProtoBuf.ProtoMember(9)]
        public double latitude { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public double longitude { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public global::POGOProtos.Data.Raid.PlayerRaidInfo raids { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
