// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: GymBadgeStats.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data.Badge
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GymBadgeStats : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong total_time_defended_ms { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint num_battles_won { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public uint num_battles_lost { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint num_berries_fed { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public uint num_deploys { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public global::System.Collections.Generic.List<global::POGOProtos.Data.Gym.GymBattle> gym_battles { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Data.Gym.GymBattle>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
