// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: ActionLogEntry.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data.Logs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ActionLogEntry : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long timestamp_ms { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public bool sfida { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public CatchPokemonLogEntry catch_pokemon
        {
            get { return __pbn__Action.Is(3) ? ((CatchPokemonLogEntry)__pbn__Action.Object) : default(CatchPokemonLogEntry); }
            set { __pbn__Action = new global::ProtoBuf.DiscriminatedUnionObject(3, value); }
        }
        public bool ShouldSerializecatch_pokemon() => __pbn__Action.Is(3);
        public void Resetcatch_pokemon() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__Action, 3);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__Action;

        [global::ProtoBuf.ProtoMember(4)]
        public FortSearchLogEntry fort_search
        {
            get { return __pbn__Action.Is(4) ? ((FortSearchLogEntry)__pbn__Action.Object) : default(FortSearchLogEntry); }
            set { __pbn__Action = new global::ProtoBuf.DiscriminatedUnionObject(4, value); }
        }
        public bool ShouldSerializefort_search() => __pbn__Action.Is(4);
        public void Resetfort_search() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__Action, 4);

        [global::ProtoBuf.ProtoMember(5)]
        public BuddyPokemonLogEntry buddy_pokemon
        {
            get { return __pbn__Action.Is(5) ? ((BuddyPokemonLogEntry)__pbn__Action.Object) : default(BuddyPokemonLogEntry); }
            set { __pbn__Action = new global::ProtoBuf.DiscriminatedUnionObject(5, value); }
        }
        public bool ShouldSerializebuddy_pokemon() => __pbn__Action.Is(5);
        public void Resetbuddy_pokemon() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__Action, 5);

        [global::ProtoBuf.ProtoMember(6)]
        public RaidRewardsLogEntry raid_rewards
        {
            get { return __pbn__Action.Is(6) ? ((RaidRewardsLogEntry)__pbn__Action.Object) : default(RaidRewardsLogEntry); }
            set { __pbn__Action = new global::ProtoBuf.DiscriminatedUnionObject(6, value); }
        }
        public bool ShouldSerializeraid_rewards() => __pbn__Action.Is(6);
        public void Resetraid_rewards() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__Action, 6);

        [global::ProtoBuf.ProtoMember(7)]
        public PasscodeRewardsLogEntry passcode_rewards
        {
            get { return __pbn__Action.Is(7) ? ((PasscodeRewardsLogEntry)__pbn__Action.Object) : default(PasscodeRewardsLogEntry); }
            set { __pbn__Action = new global::ProtoBuf.DiscriminatedUnionObject(7, value); }
        }
        public bool ShouldSerializepasscode_rewards() => __pbn__Action.Is(7);
        public void Resetpasscode_rewards() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__Action, 7);

        [global::ProtoBuf.ProtoMember(8)]
        public CompleteQuestLogEntry complete_quest
        {
            get { return __pbn__Action.Is(8) ? ((CompleteQuestLogEntry)__pbn__Action.Object) : default(CompleteQuestLogEntry); }
            set { __pbn__Action = new global::ProtoBuf.DiscriminatedUnionObject(8, value); }
        }
        public bool ShouldSerializecomplete_quest() => __pbn__Action.Is(8);
        public void Resetcomplete_quest() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__Action, 8);

        [global::ProtoBuf.ProtoMember(9)]
        public CompleteQuestStampCardLogEntry complete_quest_stamp_card
        {
            get { return __pbn__Action.Is(9) ? ((CompleteQuestStampCardLogEntry)__pbn__Action.Object) : default(CompleteQuestStampCardLogEntry); }
            set { __pbn__Action = new global::ProtoBuf.DiscriminatedUnionObject(9, value); }
        }
        public bool ShouldSerializecomplete_quest_stamp_card() => __pbn__Action.Is(9);
        public void Resetcomplete_quest_stamp_card() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__Action, 9);

        [global::ProtoBuf.ProtoMember(10)]
        public CompleteQuestPokemonEncounterLogEntry complete_quest_pokemon_encounter
        {
            get { return __pbn__Action.Is(10) ? ((CompleteQuestPokemonEncounterLogEntry)__pbn__Action.Object) : default(CompleteQuestPokemonEncounterLogEntry); }
            set { __pbn__Action = new global::ProtoBuf.DiscriminatedUnionObject(10, value); }
        }
        public bool ShouldSerializecomplete_quest_pokemon_encounter() => __pbn__Action.Is(10);
        public void Resetcomplete_quest_pokemon_encounter() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__Action, 10);

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
