// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: FortSearchLogEntry.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data.Logs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class FortSearchLogEntry : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Result result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string fort_id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<global::POGOProtos.Inventory.Item.ItemData> items { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Inventory.Item.ItemData>();

        [global::ProtoBuf.ProtoMember(4)]
        public int eggs { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public global::System.Collections.Generic.List<global::POGOProtos.Data.PokemonData> pokemon_eggs { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Data.PokemonData>();

        [global::ProtoBuf.ProtoMember(6)]
        public global::POGOProtos.Map.Fort.FortType fort_type { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public global::System.Collections.Generic.List<global::POGOProtos.Inventory.Item.ItemData> awarded_items { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Inventory.Item.ItemData>();

        [global::ProtoBuf.ProtoMember(8)]
        public global::System.Collections.Generic.List<global::POGOProtos.Inventory.Item.ItemData> bonus_items { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Inventory.Item.ItemData>();

        [global::ProtoBuf.ProtoMember(9)]
        public global::System.Collections.Generic.List<global::POGOProtos.Inventory.Item.ItemData> team_bonus_items { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Inventory.Item.ItemData>();

        [global::ProtoBuf.ProtoContract()]
        public enum Result
        {
            UNSET = 0,
            SUCCESS = 1,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
