// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: CaptureProbability.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data.Capture
{

    [global::ProtoBuf.ProtoContract()]
    public partial class CaptureProbability : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsPacked = true)]
        public global::System.Collections.Generic.List<global::POGOProtos.Inventory.Item.ItemId> pokeball_type { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Inventory.Item.ItemId>();

        [global::ProtoBuf.ProtoMember(2, IsPacked = true)]
        public float[] capture_probability { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public double reticle_difficulty_scale { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
