// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: CaptureAward.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data.Capture
{

    [global::ProtoBuf.ProtoContract()]
    public partial class CaptureAward : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsPacked = true)]
        public global::System.Collections.Generic.List<global::POGOProtos.Enums.ActivityType> activity_type { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Enums.ActivityType>();

        [global::ProtoBuf.ProtoMember(2, IsPacked = true)]
        public int[] xp { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsPacked = true)]
        public int[] candy { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsPacked = true)]
        public int[] stardust { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
