// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: PlayerAvatar.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data.Player
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerAvatar : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2)]
        public int skin { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int hair { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int shirt { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int pants { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int hat { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public int shoes { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public int avatar { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public int eyes { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public int backpack { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        [global::System.ComponentModel.DefaultValue("")]
        public string avatar_hair { get; set; } = "";

        [global::ProtoBuf.ProtoMember(12)]
        [global::System.ComponentModel.DefaultValue("")]
        public string avatar_shirt { get; set; } = "";

        [global::ProtoBuf.ProtoMember(13)]
        [global::System.ComponentModel.DefaultValue("")]
        public string avatar_pants { get; set; } = "";

        [global::ProtoBuf.ProtoMember(14)]
        [global::System.ComponentModel.DefaultValue("")]
        public string avatar_hat { get; set; } = "";

        [global::ProtoBuf.ProtoMember(15)]
        [global::System.ComponentModel.DefaultValue("")]
        public string avatar_shoes { get; set; } = "";

        [global::ProtoBuf.ProtoMember(16)]
        [global::System.ComponentModel.DefaultValue("")]
        public string avatar_eyes { get; set; } = "";

        [global::ProtoBuf.ProtoMember(17)]
        [global::System.ComponentModel.DefaultValue("")]
        public string avatar_backpack { get; set; } = "";

        [global::ProtoBuf.ProtoMember(18)]
        [global::System.ComponentModel.DefaultValue("")]
        public string avatar_gloves { get; set; } = "";

        [global::ProtoBuf.ProtoMember(19)]
        [global::System.ComponentModel.DefaultValue("")]
        public string avatar_socks { get; set; } = "";

        [global::ProtoBuf.ProtoMember(20)]
        [global::System.ComponentModel.DefaultValue("")]
        public string avatar_belt { get; set; } = "";

        [global::ProtoBuf.ProtoMember(21)]
        [global::System.ComponentModel.DefaultValue("")]
        public string avatar_glasses { get; set; } = "";

        [global::ProtoBuf.ProtoMember(22)]
        [global::System.ComponentModel.DefaultValue("")]
        public string avatar_necklace { get; set; } = "";

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
