// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: FortSettings.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Settings
{

    [global::ProtoBuf.ProtoContract()]
    public partial class FortSettings : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public double interaction_range_meters { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int max_total_deployed_pokemon { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int max_player_deployed_pokemon { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public double deploy_stamina_multiplier { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public double deploy_attack_multiplier { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public double far_interaction_range_meters { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public bool disable_gyms { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public int max_same_pokemon_at_fort { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public int max_player_total_deployed_pokemon { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
