// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: SocialClientSettings.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Settings
{

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialClientSettings : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public bool enable_social { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int max_friend_details { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int player_level_gate { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int max_friend_nickname_length { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public bool enable_add_friend_via_qr_code { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public bool enable_share_ex_pass { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialGiftCountTelemetry : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int unopened_gift_count { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int unsent_gift_count { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
