// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: NewsArticle.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data.News
{

    [global::ProtoBuf.ProtoContract()]
    public partial class NewsArticle : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<string> image_url { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string header_key { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string subheader_key { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string main_text_key { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6)]
        public long timestamp { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public NewsTemplate template { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public bool enabled { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public bool article_read { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum NewsTemplate
        {
            UNSET = 0,
            DEFAULT_TEMPLATE = 1,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
