// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: BuyItemPokeCoinsResponse.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Networking.Platform.Responses
{

    [global::ProtoBuf.ProtoContract()]
    public partial class BuyItemPokeCoinsResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Status result { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Status
        {
            UNKNOWN = 0,
            SUCCESS = 1,
            NOT_ENOUGH_POKECOINS = 3,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
