// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: GetStoreItemsResponse.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Networking.Platform.Responses
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GetStoreItemsResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Status status { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<StoreItem> items { get; } = new global::System.Collections.Generic.List<StoreItem>();

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<global::POGOProtos.Data.Player.Currency> player_currencies { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Data.Player.Currency>();

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string hash { get; set; } = "";

        [global::ProtoBuf.ProtoContract()]
        public partial class StoreItem : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            [global::System.ComponentModel.DefaultValue("")]
            public string item_id { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2)]
            public bool is_iap { get; set; }

            [global::ProtoBuf.ProtoMember(3)]
            public global::POGOProtos.Data.Player.Currency currency_to_buy { get; set; }

            [global::ProtoBuf.ProtoMember(4)]
            public global::POGOProtos.Data.Player.Currency yields_currency { get; set; }

            [global::ProtoBuf.ProtoMember(5)]
            public GetStoreItemsResponse.StoreItemInfo yields_item { get; set; }

            [global::ProtoBuf.ProtoMember(6)]
            public global::System.Collections.Generic.List<GetStoreItemsResponse.StoreTags> tags { get; } = new global::System.Collections.Generic.List<GetStoreItemsResponse.StoreTags>();

            [global::ProtoBuf.ProtoMember(7)]
            public int unknown7 { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class StoreTags : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            [global::System.ComponentModel.DefaultValue("")]
            public string tag { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2)]
            [global::System.ComponentModel.DefaultValue("")]
            public string value { get; set; } = "";

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class StoreItemInfo : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            [global::System.ComponentModel.DefaultValue("")]
            public string item_id { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2)]
            public int count { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public enum Status
        {
            UNDEFINED = 0,
            OKAY = 1,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
