// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: CameraInterpolation.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Enums
{

    [global::ProtoBuf.ProtoContract()]
    public enum CameraInterpolation
    {
        CAM_INTERP_CUT = 0,
        CAM_INTERP_LINEAR = 1,
        CAM_INTERP_SMOOTH = 2,
        CAM_INTERP_SMOOTH_ROT_LINEAR_MOVE = 3,
        CAM_INTERP_DEPENDS = 4,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
