// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: ClientTelemetryIds.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Enums
{

    [global::ProtoBuf.ProtoContract()]
    public enum ClientTelemetryIds
    {
        UNDEFINED = 0,
        BOOT_TIME = 1,
        FRAME_RATE = 2,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
