// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: Costume.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Enums
{

    [global::ProtoBuf.ProtoContract()]
    public enum Costume
    {
        COSTUME_UNSET = 0,
        HOLIDAY_2016 = 1,
        ANNIVERSARY = 2,
        ONE_YEAR_ANNIVERSARY = 3,
        HALLOWEEN_2017 = 4,
        SUMMER_2018 = 5,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
