// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: EncounterType.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Enums
{

    [global::ProtoBuf.ProtoContract()]
    public enum EncounterType
    {
        SPAWN_POINT = 0,
        INCENSE = 1,
        DISK = 2,
        POST_RAID = 3,
        STORY_QUEST = 4,
        QUEST_STAMP_CARD = 5,
        CHALLENGE_QUEST = 6,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
