// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: Filter.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Enums
{

    [global::ProtoBuf.ProtoContract()]
    public enum Filter
    {
        UNSET_FILTER = 0,
        ALL = 1,
        DEFAULT = 2,
        OWNED = 3,
        FEATURED = 4,
        PURCHASABLE = 5,
        UNLOCKABLE = 6,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
