// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: FriendshipLevelMilestone.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Enums
{

    [global::ProtoBuf.ProtoContract()]
    public enum FriendshipLevelMilestone
    {
        FRIENDSHIP_LEVEL_UNSET = 0,
        FRIENDSHIP_LEVEL_0 = 1,
        FRIENDSHIP_LEVEL_1 = 2,
        FRIENDSHIP_LEVEL_2 = 3,
        FRIENDSHIP_LEVEL_3 = 4,
        FRIENDSHIP_LEVEL_4 = 5,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
