// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: IapItemCategory.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Enums
{

    [global::ProtoBuf.ProtoContract()]
    public enum HoloIapItemCategory
    {
        IAP_CATEGORY_NONE = 0,
        IAP_CATEGORY_BUNDLE = 1,
        IAP_CATEGORY_ITEMS = 2,
        IAP_CATEGORY_UPGRADES = 3,
        IAP_CATEGORY_POKECOINS = 4,
        IAP_CATEGORY_AVATAR = 5,
        IAP_CATEGORY_AVATAR_STORE_LINK = 6,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
