// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: IdentityProvider.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Enums
{

    [global::ProtoBuf.ProtoContract()]
    public enum IdentityProvider
    {
        UNSET_IDENTITY_PROVIDER = 0,
        GOOGLE = 1,
        PTC = 2,
        FACEBOOK = 3,
        BACKGROUND = 4,
        INTERNAL = 5,
        SFIDA = 6,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
