// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: ItemEffect.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Enums
{

    [global::ProtoBuf.ProtoContract()]
    public enum ItemEffect
    {
        ITEM_EFFECT_NONE = 0,
        ITEM_EFFECT_CAP_NO_FLEE = 1000,
        ITEM_EFFECT_CAP_NO_MOVEMENT = 1002,
        ITEM_EFFECT_CAP_NO_THREAT = 1003,
        ITEM_EFFECT_CAP_TARGET_MAX = 1004,
        ITEM_EFFECT_CAP_TARGET_SLOW = 1005,
        ITEM_EFFECT_CAP_CHANCE_NIGHT = 1006,
        ITEM_EFFECT_CAP_CHANCE_TRAINER = 1007,
        ITEM_EFFECT_CAP_CHANCE_FIRST_THROW = 1008,
        ITEM_EFFECT_CAP_CHANCE_LEGEND = 1009,
        ITEM_EFFECT_CAP_CHANCE_HEAVY = 1010,
        ITEM_EFFECT_CAP_CHANCE_REPEAT = 1011,
        ITEM_EFFECT_CAP_CHANCE_MULTI_THROW = 1012,
        ITEM_EFFECT_CAP_CHANCE_ALWAYS = 1013,
        ITEM_EFFECT_CAP_CHANCE_SINGLE_THROW = 1014,
        ITEM_EFFECT_CANDY_AWARD = 1015,
        ITEM_EFFECT_FULL_MOTIVATION = 1016,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
