// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: ItemCategory.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Enums
{

    [global::ProtoBuf.ProtoContract()]
    public enum ItemCategory
    {
        ITEM_CATEGORY_NONE = 0,
        ITEM_CATEGORY_POKEBALL = 1,
        ITEM_CATEGORY_FOOD = 2,
        ITEM_CATEGORY_MEDICINE = 3,
        ITEM_CATEGORY_BOOST = 4,
        ITEM_CATEGORY_UTILITES = 5,
        ITEM_CATEGORY_CAMERA = 6,
        ITEM_CATEGORY_DISK = 7,
        ITEM_CATEGORY_INCUBATOR = 8,
        ITEM_CATEGORY_INCENSE = 9,
        ITEM_CATEGORY_XP_BOOST = 10,
        ITEM_CATEGORY_INVENTORY_UPGRADE = 11,
        ITEM_CATEGORY_EVOLUTION_REQUIREMENT = 12,
        ITEM_CATEGORY_MOVE_REROLL = 13,
        ITEM_CATEGORY_CANDY = 14,
        ITEM_CATEGORY_RAID_TICKET = 15,
        ITEM_CATEGORY_STARDUST_BOOST = 16,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
