// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: NotificationCategory.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Enums
{

    [global::ProtoBuf.ProtoContract()]
    public enum NotificationCategory
    {
        UNSET_NotificationCategory = 0,
        GYM_REMOVAL = 1,
        POKEMON_HUNGRY = 2,
        POKEMON_WON = 3,
        EXCLUSIVE_RAID_INVITE = 4,
        EXCLUSIVE_RAID_CANCELLATION = 5,
        GIFTBOX_INCOMING = 6,
        GIFTBOX_DELIVERED = 7,
        FRIENDSHIP_MILESTONE_REWARD = 8,
        GYM_BATTLE_FRIENDSHIP_INCREMENT = 9,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
