// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: PokemonTradingType.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Enums
{

    [global::ProtoBuf.ProtoContract()]
    public enum PokemonTradingType
    {
        UNSET_POKEMON_TRADING = 0,
        REGULAR_IN_POKEDEX = 1,
        SPECIAL_IN_POKEDEX = 2,
        REGULAR_NON_POKEDEX = 3,
        REGIONAL_NON_POKEDEX = 4,
        FORM_NON_POKEDEX = 5,
        LEGENDARY_NON_POKEDEX = 6,
        SHINY_NON_POKEDEX = 7,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
