// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: PokemonMovementType.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Enums
{

    [global::ProtoBuf.ProtoContract()]
    public enum PokemonMovementType
    {
        MOVEMENT_STATIC = 0,
        MOVEMENT_JUMP = 1,
        MOVEMENT_VERTICAL = 2,
        MOVEMENT_PSYCHIC = 3,
        MOVEMENT_ELECTRIC = 4,
        MOVEMENT_FLYING = 5,
        MOVEMENT_HOVERING = 6,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
