// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: RaidLevel.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Enums
{

    [global::ProtoBuf.ProtoContract()]
    public enum RaidLevel
    {
        RAID_LEVEL_UNSET = 0,
        RAID_LEVEL_1 = 1,
        RAID_LEVEL_2 = 2,
        RAID_LEVEL_3 = 3,
        RAID_LEVEL_4 = 4,
        RAID_LEVEL_5 = 5,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
