// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: Slot.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Enums
{

    [global::ProtoBuf.ProtoContract()]
    public enum Slot
    {
        UNSET_SLOT = 0,
        HAIR = 1,
        SHIRT = 2,
        PANTS = 3,
        HAT = 4,
        SHOES = 5,
        EYES = 6,
        BACKPACK = 7,
        GLOVES = 8,
        SOCKS = 9,
        BELT = 10,
        GLASSES = 11,
        NECKLACE = 12,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
