// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: SocialAction.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Enums
{

    [global::ProtoBuf.ProtoContract()]
    public enum SocialAction
    {
        UNKNOWN_SOCIAL_ACTION = 0,
        SEARCH_PLAYER = 10000,
        SEND_FRIEND_INVITE = 10002,
        CANCEL_FRIEND_INVITE = 10003,
        ACCEPT_FRIEND_INVITE = 10004,
        DECLINE_FRIEND_INVITE = 10005,
        LIST_FRIENDS = 10006,
        LIST_OUTGOING_FRIEND_INVITES = 10007,
        LIST_INCOMING_FRIEND_INVITES = 10008,
        REMOVE_FRIEND = 10009,
        LIST_FRIEND_STATUS = 10010,
        INVITE_FACEBOOK_FRIEND = 10011,
        IS_MY_FRIEND = 10012,
        CREATE_INVITE_CODE = 10013,
        REGISTER_PUSH_NOTIFICATION = 10101,
        UNREGISTER_PUSH_NOTIFICATION = 10102,
        UPDATE_NOTIFICATION = 10103,
        OPT_OUT_PUSH_NOTIFICATION_CATEGORY = 10104,
        GET_INBOX = 10105,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
