// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: TeamColor.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Enums
{

    [global::ProtoBuf.ProtoContract()]
    public enum TeamColor
    {
        NEUTRAL = 0,
        BLUE = 1,
        RED = 2,
        YELLOW = 3,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
