// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: TutorialState.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Enums
{

    [global::ProtoBuf.ProtoContract()]
    public enum TutorialState
    {
        LEGAL_SCREEN = 0,
        AVATAR_SELECTION = 1,
        ACCOUNT_CREATION = 2,
        POKEMON_CAPTURE = 3,
        NAME_SELECTION = 4,
        POKEMON_BERRY = 5,
        USE_ITEM = 6,
        FIRST_TIME_EXPERIENCE_COMPLETE = 7,
        POKESTOP_TUTORIAL = 8,
        GYM_TUTORIAL = 9,
        CHALLENGE_QUEST_TUTORIAL = 10,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
