// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: VariableName.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Enums
{

    [global::ProtoBuf.ProtoContract()]
    public enum VariableName
    {
        UNSET_VariableName = 0,
        CODE_NAME = 1,
        TEAM = 2,
        LEVEL = 3,
        EXPERIENCE = 4,
        POKECOIN_BALANCE = 5,
        STARDUST_BALANCE = 6,
        EMAIL = 7,
        LOGIN_METHOD = 8,
        GYM_ID = 1000,
        GYM_NAME = 1001,
        POKEMON_DISPLAY = 1002,
        POKEDEX_ENTRY_NUMBER = 1003,
        POKEMON_ID = 1004,
        POKEMON_NICKNAME = 1005,
        GYM_BADGE_EARNED_POINTS = 1006,
        GYM_BADGE_PROGRESS = 1007,
        GYM_BADGE_RANK = 1008,
        GYM_BADGE_IMAGE_URL = 1009,
        GYM_BADGE_LEVEL_UP = 1010,
        POKECOIN_AWARDED = 1011,
        POKECOIN_AWARDED_TODAY = 1012,
        MAX_DAILY_POKECOIN = 1013,
        BATTLES_WON = 1014,
        BATTLES_LOST = 1015,
        DEPLOYED_MILLIS = 1016,
        RAID_SEED = 1017,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
