// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: WeatherCondition.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Enums
{

    [global::ProtoBuf.ProtoContract()]
    public enum WeatherCondition
    {
        NONE = 0,
        CLEAR = 1,
        RAINY = 2,
        PARTLY_CLOUDY = 3,
        OVERCAST = 4,
        WINDY = 5,
        SNOW = 6,
        FOG = 7,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
