// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: AuthTicket.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Networking.Envelopes
{

    [global::ProtoBuf.ProtoContract()]
    public partial class AuthTicket : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public byte[] start { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong expire_timestamp_ms { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public byte[] end { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
