// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: RequestEnvelope.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Networking.Envelopes
{

    [global::ProtoBuf.ProtoContract()]
    public partial class RequestEnvelope : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int status_code { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong request_id { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<global::POGOProtos.Networking.Requests.Request> requests { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Networking.Requests.Request>();

        [global::ProtoBuf.ProtoMember(6)]
        public global::System.Collections.Generic.List<PlatformRequest> platform_requests { get; } = new global::System.Collections.Generic.List<PlatformRequest>();

        [global::ProtoBuf.ProtoMember(7)]
        public double latitude { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public double longitude { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public double accuracy { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public AuthInfo auth_info { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public AuthTicket auth_ticket { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public long ms_since_last_locationfix { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class AuthInfo : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            [global::System.ComponentModel.DefaultValue("")]
            public string provider { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2)]
            public JWT token { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public partial class JWT : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1)]
                [global::System.ComponentModel.DefaultValue("")]
                public string contents { get; set; } = "";

                [global::ProtoBuf.ProtoMember(2)]
                public int unknown2 { get; set; }

            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class PlatformRequest : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
            [global::ProtoBuf.ProtoMember(1)]
            public global::POGOProtos.Networking.Platform.PlatformRequestType type { get; set; }

            [global::ProtoBuf.ProtoMember(2)]
            public byte[] request_message { get; set; }

        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
