// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: BattleActionType.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data.Battle
{

    [global::ProtoBuf.ProtoContract()]
    public enum BattleActionType
    {
        ACTION_UNSET = 0,
        ACTION_ATTACK = 1,
        ACTION_DODGE = 2,
        ACTION_SPECIAL_ATTACK = 3,
        ACTION_SWAP_POKEMON = 4,
        ACTION_FAINT = 5,
        ACTION_PLAYER_JOIN = 6,
        ACTION_PLAYER_QUIT = 7,
        ACTION_VICTORY = 8,
        ACTION_DEFEAT = 9,
        ACTION_TIMED_OUT = 10,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
