// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: BattleParticipant.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data.Battle
{

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleParticipant : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public BattlePokemonInfo active_pokemon { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::POGOProtos.Data.Player.PlayerPublicProfile trainer_public_profile { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<BattlePokemonInfo> reverse_pokemon { get; } = new global::System.Collections.Generic.List<BattlePokemonInfo>();

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<BattlePokemonInfo> defeated_pokemon { get; } = new global::System.Collections.Generic.List<BattlePokemonInfo>();

        [global::ProtoBuf.ProtoMember(5)]
        public global::System.Collections.Generic.List<global::POGOProtos.Map.Pokemon.LobbyPokemon> lobby_pokemon { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Map.Pokemon.LobbyPokemon>();

        [global::ProtoBuf.ProtoMember(6)]
        public int damage_dealt { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public bool super_effective_charge_move { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public bool weather_boosted { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public global::POGOProtos.Enums.FriendshipLevelMilestone highest_friendship_milestone { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public global::System.Collections.Generic.List<string> friend_codename { get; } = new global::System.Collections.Generic.List<string>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
