// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: BattleAction.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data.Battle
{

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleAction : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public BattleActionType type { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long action_start_ms { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int duration_ms { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int energy_delta { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int attacker_index { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public int target_index { get; set; }

        [global::ProtoBuf.ProtoMember(8, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong active_pokemon_id { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public BattleParticipant player_joined { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public BattleResults battle_results { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public long damage_windows_start_timestamp_ms { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public long damage_windows_end_timestamp_ms { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public BattleParticipant player_left { get; set; }

        [global::ProtoBuf.ProtoMember(14, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong target_pokemon_id { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public global::POGOProtos.Data.Friends.LeveledUpFriends leveled_up_friends { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
