// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: Battle.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data.Battle
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Battle : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long battle_start_ms { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long battle_end_ms { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string battle_id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        public BattleParticipant defender { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public BattleLog battle_log { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public BattleParticipant attacker { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public global::POGOProtos.Enums.WeatherCondition weather_condition { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public global::POGOProtos.Enums.FriendshipLevelMilestone highest_friendship_milestone { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
