// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: BattleResults.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data.Battle
{

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleResults : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::POGOProtos.Data.Gym.GymState gym_state { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<BattleParticipant> attackers { get; } = new global::System.Collections.Generic.List<BattleParticipant>();

        [global::ProtoBuf.ProtoMember(3, IsPacked = true)]
        public int[] player_xp_awarded { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public long next_defender_pokemon_id { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int gym_points_delta { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public global::POGOProtos.Data.Gym.GymStatusAndDefenders gym_status { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public global::System.Collections.Generic.List<global::POGOProtos.Data.Raid.Participation> participation { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Data.Raid.Participation>();

        [global::ProtoBuf.ProtoMember(8)]
        public global::System.Collections.Generic.List<global::POGOProtos.Inventory.Loot> raid_item_rewards { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Inventory.Loot>();

        [global::ProtoBuf.ProtoMember(9)]
        public global::System.Collections.Generic.List<global::POGOProtos.Data.Raid.RaidEncounter> post_raid_encounter { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Data.Raid.RaidEncounter>();

        [global::ProtoBuf.ProtoMember(10)]
        public global::System.Collections.Generic.List<global::POGOProtos.Data.Badge.AwardedGymBadge> gym_badge { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Data.Badge.AwardedGymBadge>();

        [global::ProtoBuf.ProtoMember(11)]
        public global::System.Collections.Generic.List<global::POGOProtos.Inventory.Loot> default_raid_item_rewards { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Inventory.Loot>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
