// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: BattleType.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data.Battle
{

    [global::ProtoBuf.ProtoContract()]
    public enum BattleType
    {
        BATTLE_TYPE_UNSET = 0,
        BATTLE_TYPE_NORMAL = 1,
        BATTLE_TYPE_TRAINING = 2,
        BATTLE_TYPE_RAID = 3,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
