// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: BattleState.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data.Battle
{

    [global::ProtoBuf.ProtoContract()]
    public enum BattleState
    {
        STATE_UNSET = 0,
        ACTIVE = 1,
        VICTORY = 2,
        DEFEATED = 3,
        TIMED_OUT = 4,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
