// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: BattleLog.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data.Battle
{

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleLog : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [global::ProtoBuf.ProtoMember(1)]
        public BattleState state { get; set; }

        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [global::ProtoBuf.ProtoMember(2)]
        public BattleType battle_type { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public long server_ms { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<BattleAction> battle_actions { get; } = new global::System.Collections.Generic.List<BattleAction>();

        [global::ProtoBuf.ProtoMember(5)]
        public long battle_start_timestamp_ms { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public long battle_end_timestamp_ms { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
