// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: ClientQuest.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data.Quests
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientQuest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Quest quest { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public QuestDisplay quest_display { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class QuestDisplay : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            [global::System.ComponentModel.DefaultValue("")]
            public string quest_id { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2)]
            public global::System.Collections.Generic.List<QuestDialog> dialog { get; } = new global::System.Collections.Generic.List<QuestDialog>();

            [global::ProtoBuf.ProtoMember(3)]
            [global::System.ComponentModel.DefaultValue("")]
            public string description { get; set; } = "";

            [global::ProtoBuf.ProtoMember(4)]
            [global::System.ComponentModel.DefaultValue("")]
            public string title { get; set; } = "";

            [global::ProtoBuf.ProtoMember(5)]
            public int slot { get; set; }

            [global::ProtoBuf.ProtoMember(6)]
            public global::System.Collections.Generic.List<QuestDisplay> subdisplay { get; } = new global::System.Collections.Generic.List<QuestDisplay>();

            [global::ProtoBuf.ProtoMember(7)]
            public bool story_ending_quest { get; set; }

            [global::ProtoBuf.ProtoMember(8)]
            [global::System.ComponentModel.DefaultValue("")]
            public string story_ending_description { get; set; } = "";

        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
