// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: QuestCondition.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data.Quests
{

    [global::ProtoBuf.ProtoContract()]
    public partial class QuestCondition : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [global::ProtoBuf.ProtoMember(1)]
        public ConditionType type { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public WithPokemonType with_pokemon_type { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public WithPokemonCategory with_pokemon_category { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public WithWeatherBoost with_weather_boost { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public WithDailyCaptureBonus with_daily_capture_bonus { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public WithDailySpinBonus with_daily_spin_bonus { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public WithWinRaidStatus with_win_raid_status { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public WithRaidLevel with_raid_level { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public WithThrowType with_throw_type { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public WithWinGymBattleStatus with_win_gym_battle_status { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public WithSuperEffectiveChargeMove with_super_effective_charge_move { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public WithItem with_item { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public WithUniquePokestop with_unique_pokestop { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        public WithQuestContext with_quest_context { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public WithBadgeType with_badge_type { get; set; }

        [global::ProtoBuf.ProtoMember(16)]
        public WithPlayerLevel with_player_level { get; set; }

        [global::ProtoBuf.ProtoMember(17)]
        public WithWinBattleStatus with_win_battle_status { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class WithPokemonType : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsPacked = true)]
            public global::System.Collections.Generic.List<global::POGOProtos.Enums.PokemonType> pokemon_type { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Enums.PokemonType>();

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class WithWeatherBoost : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class WithPokemonCategory : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            [global::System.ComponentModel.DefaultValue("")]
            public string category_name { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2, IsPacked = true)]
            public global::System.Collections.Generic.List<global::POGOProtos.Enums.PokemonId> pokemon_ids { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Enums.PokemonId>();

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class WithDailyCaptureBonus : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class WithDailySpinBonus : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class WithWinRaidStatus : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class WithRaidLevel : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsPacked = true)]
            public global::System.Collections.Generic.List<global::POGOProtos.Enums.RaidLevel> raid_level { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Enums.RaidLevel>();

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class WithThrowType : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
            [global::ProtoBuf.ProtoMember(1)]
            public global::POGOProtos.Enums.ActivityType throw_type { get; set; }

            [global::ProtoBuf.ProtoMember(2)]
            public bool hit { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class WithCurveBall : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class WithWinGymBattleStatus : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class WithSuperEffectiveChargeMove : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class WithItem : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
            [global::ProtoBuf.ProtoMember(1)]
            public global::POGOProtos.Inventory.Item.ItemId item { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class WithUniquePokestop : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class WithQuestContext : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
            [global::ProtoBuf.ProtoMember(1)]
            public Context context { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public enum Context
            {
                UNSET = 0,
                STORY_QUEST = 1,
                CHALLENGE_QUEST = 2,
            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class WithBadgeType : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsPacked = true)]
            public global::System.Collections.Generic.List<global::POGOProtos.Enums.BadgeType> badge_type { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Enums.BadgeType>();

            [global::ProtoBuf.ProtoMember(2)]
            public int badge_rank { get; set; }

            [global::ProtoBuf.ProtoMember(3)]
            public int amount { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class WithPlayerLevel : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            public int level { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class WithWinBattleStatus : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

        [global::ProtoBuf.ProtoContract()]
        public enum ConditionType
        {
            UNSET = 0,
            WITH_POKEMON_TYPE = 1,
            WITH_POKEMON_CATEGORY = 2,
            WITH_WEATHER_BOOST = 3,
            WITH_DAILY_CAPTURE_BONUS = 4,
            WITH_DAILY_SPIN_BONUS = 5,
            WITH_WIN_RAID_STATUS = 6,
            WITH_RAID_LEVEL = 7,
            WITH_THROW_TYPE = 8,
            WITH_WIN_GYM_BATTLE_STATUS = 9,
            WITH_SUPER_EFFECTIVE_CHARGE = 10,
            WITH_ITEM = 11,
            WITH_UNIQUE_POKESTOP = 12,
            WITH_QUEST_CONTEXT = 13,
            WITH_THROW_TYPE_IN_A_ROW = 14,
            WITH_CURVE_BALL = 15,
            WITH_BADGE_TYPE = 16,
            WITH_PLAYER_LEVEL = 17,
            WITH_WIN_BATTLE_STATUS = 18,
            WITH_NEW_FRIEND = 19,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
