// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: QuestPokemonEncounter.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data.Quests
{

    [global::ProtoBuf.ProtoContract()]
    public partial class QuestPokemonEncounter : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string quest_id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public global::POGOProtos.Data.PokemonData pokemon { get; set; }

        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [global::ProtoBuf.ProtoMember(3)]
        public global::POGOProtos.Enums.EncounterType encounter_type { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public bool is_hidden_ditto { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public global::POGOProtos.Data.PokemonData ditto { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
