// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: Quest.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data.Quests
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Quest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::POGOProtos.Enums.QuestType quest_type { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public DailyQuest daily_quest { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public MultiPartQuest multi_part { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public CatchPokemonQuest catch_pokemon { get; set; }

        [global::ProtoBuf.ProtoMember(100)]
        [global::System.ComponentModel.DefaultValue("")]
        public string quest_id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(101)]
        public long quest_seed { get; set; }

        [global::ProtoBuf.ProtoMember(102)]
        public Context quest_context { get; set; }

        [global::ProtoBuf.ProtoMember(103)]
        [global::System.ComponentModel.DefaultValue("")]
        public string template_id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(104)]
        public int progress { get; set; }

        [global::ProtoBuf.ProtoMember(105)]
        public QuestGoal goal { get; set; }

        [global::ProtoBuf.ProtoMember(106)]
        public Status status { get; set; }

        [global::ProtoBuf.ProtoMember(107)]
        public global::System.Collections.Generic.List<QuestReward> quest_rewards { get; } = new global::System.Collections.Generic.List<QuestReward>();

        [global::ProtoBuf.ProtoMember(108)]
        public long creation_timestamp_ms { get; set; }

        [global::ProtoBuf.ProtoMember(109)]
        public long last_update_timestamp_ms { get; set; }

        [global::ProtoBuf.ProtoMember(110)]
        public long compeletion_timestamp_ms { get; set; }

        [global::ProtoBuf.ProtoMember(111)]
        [global::System.ComponentModel.DefaultValue("")]
        public string fort_id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(112)]
        public bool admin_generated { get; set; }

        [global::ProtoBuf.ProtoMember(113)]
        public bool stamp_count_override_enabled { get; set; }

        [global::ProtoBuf.ProtoMember(114)]
        public int stamp_count_override { get; set; }

        [global::ProtoBuf.ProtoMember(115)]
        public long s2_cell_id { get; set; }

        [global::ProtoBuf.ProtoMember(116)]
        public int story_quest_template_version { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class MultiPartQuest : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            public global::System.Collections.Generic.List<Quest> sub_quests { get; } = new global::System.Collections.Generic.List<Quest>();

        }

        [global::ProtoBuf.ProtoContract()]
        public enum Context
        {
            UNSET = 0,
            STORY_QUEST = 1,
            CHALLENGE_QUEST = 2,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum Status
        {
            STATUS_UNDEFINED = 0,
            STATUS_ACTIVE = 1,
            STATUS_COMPLETED = 2,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
