// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: QuestStampCard.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data.Quests
{

    [global::ProtoBuf.ProtoContract()]
    public partial class QuestStampCard : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<QuestStamp> stamp { get; } = new global::System.Collections.Generic.List<QuestStamp>();

        [global::ProtoBuf.ProtoMember(2)]
        public int target { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int remaining_daily_stamps { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string icon_url { get; set; } = "";

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
