// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: BattleAttributes.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Settings.Master.Item
{

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleAttributes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public float sta_percent { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public float atk_percent { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public float def_percent { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public float duration_s { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
