// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: FoodAttributes.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Settings.Master.Item
{

    [global::ProtoBuf.ProtoContract()]
    public partial class FoodAttributes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsPacked = true)]
        public global::System.Collections.Generic.List<global::POGOProtos.Enums.ItemEffect> item_effect { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Enums.ItemEffect>();

        [global::ProtoBuf.ProtoMember(2, IsPacked = true)]
        public float[] item_effect_percent { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public float growth_percent { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public float berry_multiplier { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public float remote_berry_multiplier { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
