// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: IncenseAttributes.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Settings.Master.Item
{

    [global::ProtoBuf.ProtoContract()]
    public partial class IncenseAttributes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int incense_lifetime_seconds { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsPacked = true)]
        public global::System.Collections.Generic.List<global::POGOProtos.Enums.PokemonType> pokemon_type { get; } = new global::System.Collections.Generic.List<global::POGOProtos.Enums.PokemonType>();

        [global::ProtoBuf.ProtoMember(3)]
        public float pokemon_incense_type_probability { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int standing_time_between_encounters_seconds { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int moving_time_between_encounter_seconds { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int distance_required_for_shorter_interval_meters { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public int pokemon_attracted_length_sec { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
