// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: PokeballAttributes.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Settings.Master.Item
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PokeballAttributes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::POGOProtos.Enums.ItemEffect item_effect { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public float capture_multi { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public float capture_multi_effect { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public float item_effect_mod { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
