// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: AvatarCustomization.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Data.Avatar
{

    [global::ProtoBuf.ProtoContract()]
    public partial class AvatarCustomization : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string avatar_template_id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, IsPacked = true)]
        public global::System.Collections.Generic.List<Label> labels { get; } = new global::System.Collections.Generic.List<Label>();

        [global::ProtoBuf.ProtoContract()]
        public enum Label
        {
            UNSET_LABEL = 0,
            DEFAULT = 1,
            OWNED = 2,
            FEATURED = 3,
            NEW = 4,
            SALE = 5,
            PURCHASABLE = 6,
            UNLOCKABLE = 7,
            VIEWED = 8,
            LOCKED_PURCHASABLE = 9,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
