// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: PlatformRequestType.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Networking.Platform
{

    [global::ProtoBuf.ProtoContract()]
    public enum PlatformRequestType
    {
        METHOD_UNSET = 0,
        BUY_ITEM_POKECOINS = 2,
        BUY_ITEM_ANDROID = 3,
        BUY_ITEM_IOS = 4,
        GET_STORE_ITEMS = 5,
        SEND_ENCRYPTED_SIGNATURE = 6,
        UNKNOWN_PTR_8 = 8,
        JOIN_EVENT = 9,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
