// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: ClientWeather.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Map.Weather
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientWeather : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long s2_cell_id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public DisplayWeather display_weather { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public GameplayWeather gameplay_weather { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<WeatherAlert> alerts { get; } = new global::System.Collections.Generic.List<WeatherAlert>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
