// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: CameraAttributes.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Settings.Master.Pokemon
{

    [global::ProtoBuf.ProtoContract()]
    public partial class CameraAttributes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public float disk_radius_m { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public float cylinder_radius_m { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public float cylinder_height_m { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public float cylinder_ground_m { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public float shoulder_mode_scale { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
