// ***** This is for GAME_MASTER files. *****
// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: StatsAttributes.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace POGOProtos.Settings.Master.Pokemon
{

    [global::ProtoBuf.ProtoContract()]
    public partial class StatsAttributes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int base_stamina { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int base_attack { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int base_defense { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public int dodge_energy_delta { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
